In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])

In [11]:
ser2 = Series([3,4], index=['X', 'Y'])

In [12]:
ser1

T    0
U    1
V    2
dtype: int64

In [13]:
ser2

X    3
Y    4
dtype: int64

In [15]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1, ser2], axis=1)

C:\Users\michael.manna\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [17]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [18]:
dframe1 = DataFrame(np.random.rand(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.rand(3,3), columns=['Y', 'Q', 'X'])

In [19]:
dframe1

X         Y         Z
0  0.167154  0.008549  0.828579
1  0.960392  0.147018  0.534980
2  0.485368  0.246534  0.404554
3  0.509430  0.608648  0.801777

In [20]:
dframe2

Y         Q         X
0  0.277682  0.224721  0.136837
1  0.483941  0.824185  0.510300
2  0.046998  0.338658  0.414535

In [22]:
pd.concat([dframe1, dframe2])

C:\Users\michael.manna\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.167154  0.008549  0.828579
1       NaN  0.960392  0.147018  0.534980
2       NaN  0.485368  0.246534  0.404554
3       NaN  0.509430  0.608648  0.801777
0  0.224721  0.136837  0.277682       NaN
1  0.824185  0.510300  0.483941       NaN
2  0.338658  0.414535  0.046998       NaN

In [24]:
pd.concat([dframe1, dframe2],sort=True)

Q         X         Y         Z
0       NaN  0.167154  0.008549  0.828579
1       NaN  0.960392  0.147018  0.534980
2       NaN  0.485368  0.246534  0.404554
3       NaN  0.509430  0.608648  0.801777
0  0.224721  0.136837  0.277682       NaN
1  0.824185  0.510300  0.483941       NaN
2  0.338658  0.414535  0.046998       NaN

In [25]:
pd.concat([dframe1, dframe2], sort=False)

X         Y         Z         Q
0  0.167154  0.008549  0.828579       NaN
1  0.960392  0.147018  0.534980       NaN
2  0.485368  0.246534  0.404554       NaN
3  0.509430  0.608648  0.801777       NaN
0  0.136837  0.277682       NaN  0.224721
1  0.510300  0.483941       NaN  0.824185
2  0.414535  0.046998       NaN  0.338658

In [26]:
pd.concat([dframe1, dframe2], ignore_index=True, sort=True)

Q         X         Y         Z
0       NaN  0.167154  0.008549  0.828579
1       NaN  0.960392  0.147018  0.534980
2       NaN  0.485368  0.246534  0.404554
3       NaN  0.509430  0.608648  0.801777
4  0.224721  0.136837  0.277682       NaN
5  0.824185  0.510300  0.483941       NaN
6  0.338658  0.414535  0.046998       NaN