In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 1.00513929, -0.63069875, -0.4519562 , -0.63782001,  1.74276291,
       -0.02996429, -1.59968712, -0.00229317,  1.11496189, -0.74737801])

In [7]:
B = np.random.randn(10)
B

array([-0.22987909,  0.01684975,  0.4186602 ,  0.85642989, -1.25165163,
       -0.41679822,  0.1440533 , -1.3614226 , -0.90127412,  0.96610878])

In [8]:
#Binary Functions
np.add(A,B)

array([ 0.77526019, -0.61384901, -0.033296  ,  0.21860988,  0.49111128,
       -0.44676251, -1.45563382, -1.36371577,  0.21368777,  0.21873077])

In [9]:
np.maximum(A,B)

array([ 1.00513929,  0.01684975,  0.4186602 ,  0.85642989,  1.74276291,
       -0.02996429,  0.1440533 , -0.00229317,  1.11496189,  0.96610878])

In [10]:
np.minimum(A,B)

array([-0.22987909, -0.63069875, -0.4519562 , -0.63782001, -1.25165163,
       -0.41679822, -1.59968712, -1.3614226 , -0.90127412, -0.74737801])